#!/bin/bash

#Author:April
#Date: Feb 20,2023
#Description: Script to install SonarQube on CentOS 7

#su - vagrant
#Step 1: Java 11 installation


sudo yum update -y

sudo yum install java-11-openjdk-devel -y

sudo yum install java-11-openjdk -y
#Step 2: Download SonarQube latest versions on your server

cd /opt

sudo yum install wget -y

sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip

#Step 3: Extract packages
sudo yum install unzip
sudo unzip /opt/sonarqube-9.3.0.51899.zip
#To install it. Now, unzip the previously installed package:

sudo unzip /opt/sonarqube-9.3.0.51899.zip
#Step 4: Change ownership to the user and Switch to Linux binaries directory to start service
sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899

cd /opt
cd sonarqube-9.3.0.51899
cd bin
cd linux-86-64
sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --permanent --add-port=9000/tcp
sudo firewall-cmd --reload
# ./sonar.sh start